### ISSUE TITLE
protocol Enumerable not implemented for nil 

### ISSUE THREAD

**Issue by kpanic** [liquidz/vivi.vim#9]
Hi @liquidz !
First of all thank you for this effort!

However, I am not able to get it to work.
I am using Vundle and my `Plugin` are:

```
Plugin 'liquidz/vivi.vim'
    let g:vivi_enable_omni_completion = 1
    let g:vivi_enable_auto_syntax_checking = 1
    let g:vivi_enable_auto_warm_up_iex = 1

    " deps
    Plugin 'Shougo/vimproc.vim',
    Plugin 'Shougo/neocomplete.vim',
    Plugin 'thinca/vim-quickrun',
    Plugin 'thinca/vim-ref',
    Plugin 'osyo-manga/shabadou.vim',
    Plugin 'osyo-manga/vim-watchdogs'
```

Elixir 1.1.1 and erlang 18 here

This happens when I open a `test.ex` file and I type `List.`

```
List.
~    ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil                               f                           
~        (elixir) lib/enum.ex:1: Enumerable.impl_for!/1                                                     f                           
~        (elixir) lib/enum.ex:112: Enumerable.reduce/3                                                      f                           
~        (elixir) lib/enum.ex:1400: Enum.reduce/3                                                           f                           
~        (elixir) lib/enum.ex:1047: Enum.map/2                                                              f                           
~                 /home/beatpanic/.vim/bundle/vivi.vim/elixir/lib/vivi.ex:25: Vivi.print_module_functions/1 f   
```

What am I missing? Thank you!

**Comment by kpanic** [comment]
FYI

Turns out that if I disable:

```
    let g:vivi_enable_auto_warm_up_iex = 0
```

I get (with crtl-x ctrl-o) autocomplete correctly!

**Comment by liquidz** [comment]
Could you try to add `let g:neocomplete#enable_at_startup = 1` to .vimrc ?
- test.vimrc

``` vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'liquidz/vivi.vim'
    let g:vivi_enable_omni_completion = 1
    let g:vivi_enable_auto_syntax_checking = 1
    let g:vivi_enable_auto_warm_up_iex = 1

    " deps
    Plugin 'elixir-lang/vim-elixir'
    Plugin 'Shougo/vimproc.vim'
    Plugin 'Shougo/neocomplete.vim'
        let g:neocomplete#enable_at_startup = 1
    Plugin 'thinca/vim-quickrun'
    Plugin 'thinca/vim-ref'
    Plugin 'osyo-manga/shabadou.vim'
    Plugin 'osyo-manga/vim-watchdogs'

call vundle#end()
filetype plugin indent on
```
- launch vim

```
vim -u test.vimrc test.ex
```

**Comment by kpanic** [comment]
`test.vimrc` works like a charm
Adding to my vimrc `let g:neocomplete#enable_at_startup = 1` works too! thank you! :santa: 
Should I close the issue?
Thank you!

**Comment by liquidz** [comment]
:+1:
